/* src/test/setupTests.ts - autogenerated test setup (robust)
   - sets runtime env defaults for tests
   - installs safe logger stub & patches imported logger modules
   - mocks expo native modules and msal/graph/copilot wrappers for unit tests
*/
process.env.SESSION_SIGNING_KEY = process.env.SESSION_SIGNING_KEY || 'test-session-key';
process.env.AZURE_CLIENT_ID = process.env.AZURE_CLIENT_ID || 'test-client-id';
process.env.AZURE_TENANT_ID = process.env.AZURE_TENANT_ID || 'test-tenant-id';
process.env.OIDC_REDIRECT_URI = process.env.OIDC_REDIRECT_URI || 'http://localhost:3000/auth/callback';
process.env.EXPO_PUBLIC_BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL || 'http://localhost:3000';

const noopWithMeta = (..._args: any[]) => {};
const safeLogger = {
  info: noopWithMeta,
  warn: noopWithMeta,
  error: noopWithMeta,
  debug: noopWithMeta,
  child: () => safeLogger,
};
// expose on global in case code references global.logger
;(global as any).logger = safeLogger;

// Try to patch common logger module import paths so `import logger from '../utils/logger'`
// or `import { logger } from '@/src/utils/logger'` resolves to safeLogger
const candidateLoggerPaths = [
  '../utils/logger',
  '../../src/utils/logger',
  'src/utils/logger',
  '@/src/utils/logger',
  '@/utils/logger',
  './utils/logger',
  '../src/utils/logger'
];
for (const p of candidateLoggerPaths) {
  try {
    // require.resolve may throw; avoid ESM issues by try/catch
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require.resolve(p);
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const m = require(p);
    if (m) {
      // CommonJS export object
      if (typeof m === 'object') {
        m.info = m.info || safeLogger.info;
        m.warn = m.warn || safeLogger.warn;
        m.error = m.error || safeLogger.error;
        m.debug = m.debug || safeLogger.debug;
        // also patch default if present
        if (m.default && typeof m.default === 'object') {
          m.default.info = m.default.info || safeLogger.info;
          m.default.warn = m.default.warn || safeLogger.warn;
          m.default.error = m.default.error || safeLogger.error;
          m.default.debug = m.default.debug || safeLogger.debug;
        }
      }
    }
  } catch (e) {
    // ignore unresolved paths
  }
}

// vitest mocking helpers
import { vi } from 'vitest';

// Mock expo modules used by mobile tests
vi.mock('expo-auth-session', () => {
  return {
    startAsync: async (opts: any) => ({ type: 'success', params: { code: 'dummy-code', state: opts?.state || 'state' } }),
    makeRedirectUri: (_opts?: any) => 'exp://localhost',
    generateRandom: () => 'random-string',
    // if code uses perform or similar names, include them
    exchangeCodeAsync: async () => ({ access_token: 'dummy' }),
  };
});

vi.mock('expo-secure-store', () => {
  const store: Record<string, string> = {};
  return {
    setItemAsync: async (k: string, v: string) => { store[k] = v; },
    getItemAsync: async (k: string) => store[k] ?? null,
    deleteItemAsync: async (k: string) => { delete store[k]; },
  };
});

// provide a generic expo-constants mock (some modules access it)
vi.mock('expo-constants', () => ({ manifest: {}, appOwnership: 'standalone' }));

// Robust msal mock - return string for getAuthCodeUrl (some code expects string)
// and accessToken / idToken for acquireTokenByCode
vi.mock('msal', () => {
  const MockConfidentialClient = function () {
    return {
      // msal getAuthCodeUrl usually returns a string URL
      getAuthCodeUrl: async (_params: any) => 'https://login.microsoftonline.com/dummy/authorize',
      acquireTokenByCode: async (_params: any) => ({ accessToken: 'dummy-access-token', idToken: 'dummy-id-token', account: {} }),
      acquireTokenSilent: async (_params: any) => ({ accessToken: 'dummy-access-token' }),
    };
  };
  return { ConfidentialClientApplication: MockConfidentialClient, PublicClientApplication: MockConfidentialClient };
});

// Mock Microsoft365AgentService used by middleware tests. Tests expect it to throw
// when uninitialized and behave after initializeClient is called.
vi.mock('../integrations/microsoft-365-agent', () => {
  return {
    Microsoft365AgentService: class {
      private _initialized = false;
      async initializeClient(_token: string) { this._initialized = true; return; }
      async processQuery(_q: string) {
        if (!this._initialized) throw new Error('Graph client not initialized');
        // return shape tests expect
        return { response: 'mocked', timestamp: Date.now() };
      }
      async getUserInfo() {
        if (!this._initialized) throw new Error('Graph client not initialized');
        return { id: 'user-1', displayName: 'Test User' };
      }
    }
  };
});

// Mock Copilot client wrapper if present
try {
  vi.mock('../integrations/copilot-client', () => {
    return {
      CopilotService: class {
        async startConversation() { return { conversationId: 'conv-test' }; }
        async askQuestion(_m: string, _convId?: string) { return { text: 'mock reply' }; }
      }
    };
  });
} catch (e) {
  // ignore if module not present
}

// Provide a minimal global fetch to protect code that expects fetch
if (typeof (global as any).fetch === 'undefined') {
  (global as any).fetch = async () => ({ ok: true, json: async () => ({}) });
}
